services:
  config-server:
    image: config-server
    container_name: config-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./src/main/resources/config/global.properties:/src/main/resources/config/global.properties
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
      - EUREKA_CLIENT_FETCH_REGISTRY=${EUREKA_CLIENT_FETCH_REGISTRY}
    networks:
      - spring-microservice

networks:
  spring-microservice:
    external: true