services:
  order-service:
    image: order-service-1
    container_name: order-service-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
      - EUREKA_CLIENT_FETCH_REGISTRY=${EUREKA_CLIENT_FETCH_REGISTRY}
      # - SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
      # - SPRING_REDIS_PORT=${SPRING_REDIS_PORT}
      # - SPRING_REDIS_PASSWORD=${SPRING_REDIS_PASSWORD}
    networks:
      - spring-microservice
      
networks:
  spring-microservice:
    external: true